server:
  port: 8098
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/academy
    username: admin
    password: Barcelona119
    driver-class-name: com.mysql.cj.jdbc.Driver
swagger:
  enabled: true